name: self-hosted runner
on:
  push:
    branches: [feature/**]
  workflow_dispatch: 

jobs:
  test-local:
    runs-on: [self-hosted]
    #defaults:
    #  run:
    #    working-directory: "003"

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    
    - name: system info
      run: |
        echo "ğŸ  Hostname: $(hostname)"
        echo "ğŸ”§ Usuario: $(whoami)"
        echo "ğŸ•“ Fecha: $(date)"